Changing init.d file to a standard format

diff --git a/gowebserver_1.0/etc/init.d/gowebserver b/gowebserver_1.0/etc/init.d/gowebserver
--- a/gowebserver_1.0/etc/init.d/gowebserver
+++ b/gowebserver_1.0/etc/init.d/gowebserver
@@ -1,21 +1,69 @@
-#!/bin/sh
+#! /bin/sh
 ### BEGIN INIT INFO
 # Provides:             gowebserver
-# Short-Description:    gowebserver test app
-# Description:          gowebserver test app for Spinnaker
+# Required-Start:       $syslog $remote_fs
+# Required-Stop:        $syslog $remote_fs
+# Should-Start:         $local_fs
+# Should-Stop:          $local_fs
+# Default-Start:        2 3 4 5
+# Default-Stop:         0 1 6
+# Short-Description:    gowebserver
+# Description:          gowebserver
 ### END INIT INFO
 
 
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+DAEMON=/usr/local/bin/gowebserver
+NAME=gowebserver
+DESC=gowebserver
+
+RUNDIR=/var/run/gowebserver
+PIDFILE=$RUNDIR/gowebserver.pid
+
+test -x $DAEMON || exit 0
+
+if [ -r /etc/default/$NAME ]
+then
+        . /etc/default/$NAME
+fi
+. /lib/lsb/init-functions
 
 set -e
 
-if start-stop-daemon --start --quiet --pidfile /var/run/gowebserver.pid --exec /usr/local/bin/gowebserver
-then
-	echo "=====> gowebserver started successfully"
-else
-	echo "=====> gowebserver failed to start"
-	exit 1
-fi
+case "$1" in
+  start)
+        echo -n "Starting $DESC: "
+        mkdir -p $RUNDIR
+        touch $PIDFILE
+
+        if start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON
+        then
+                echo "=======>>>>> GOWEBSERVER started successfully. - $NAME"
+        else
+                echo "=======>>>>> GOWEBSERVER failed to start - $NAME"
+        fi
+        ;;
+  stop)
+        echo -n "Stopping $DESC: "
+        if start-stop-daemon --stop --retry forever/TERM/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
+        then
+                echo "=======>>>>> Stopped $NAME."
+        else
+                echo "=======>>>>> Unable to stop $NAME"
+        fi
+        rm -f $PIDFILE
+        sleep 1
+        ;;
+
+  restart|force-reload)
+        ${0} stop
+        ${0} start
+        ;;
+
+  *)
+        echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
+        exit 1
+        ;;
+esac
 
 exit 0
